---
# Homepage configuration
# See https://fontawesome.com/v6/search for icons options

title: KodeLab Dashboard
subtitle: Morgan Kryze's
logo: "assets/icons/mrgnkrz.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

# Optional theme customization
theme: default

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars 
colors:
  light:
    highlight-primary: "#247B7B"
    highlight-secondary: "#44A1A0"
    highlight-hover: "#78CDD7"
    background: "#f5f5f5"
    card-background: "#fffffA"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#78CDD7"
    link-hover: "#363636"
  dark:
    highlight-primary: "#247B7B"
    highlight-secondary: "#44A1A0"
    highlight-hover: "#78CDD7"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#78CDD7"
    link-hover: "#ffdd57"

message:
  style: is-dark
  title: Welcome!
  icon: fa-solid fa-door-open
  content: 'This is my personnal kodelab dashboard. <br /> You will find useful links for coding I use and also my <b>self-hosted</b> applications. <br /> <br /> Feel free to <a href="mailto:morgan@kodelab.fr">get in touch</a>!'

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: My GitHub profile
    icon: fab fa-github
    url: "https://github.com/MorganKryze"
    target: "_blank"
  - name: Get in touch
    icon: fa-regular fa-envelope
    url: "mailto:morgan@kodelab.fr"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

services:
  - name: Server
    icon: fa-solid fa-server
    items:
      - name: Portainer dashboard
        logo: "assets/tools/portainer.png"
        subtitle: Manage all containers
        tag: self-hosted
        keywords: projetcs docker portainer
        url: "https://portainer.mykodelab.dev/"
        target: "_blank"
      - name: Cloudflare dashboard
        icon: fa-brands fa-cloudflare
        subtitle: Manage DNS and tunnels
        keywords: cloudflare DNS tunnels hostname
        url: "https://one.dash.cloudflare.com/"
        target: "_blank"
      - name: OVH Cloud
        logo: "assets/tools/ovh.png"
        subtitle: Domain name provider
        keywords: ovh provider domain name vps
        url: "https://www.ovh.com/"
        target: "_blank"

  - name: Tools
    icon: fa-solid fa-tools
    items:
      - name: Le Chat Mistral
        logo: "assets/tools/mistral.png"
        subtitle: Coding oriented LLM
        keywords: llm code performant
        url: "https://chat.mistral.ai/chat"
        target: "_blank"
      - name: Deepl
        logo: "assets/tools/deepl.png"
        subtitle: Best translator available
        keywords: deepl translator faithful
        url: "https://www.deepl.com/"
        target: "_blank"
      - name: Real favicon generator
        logo: "assets/tools/realfav.png"
        subtitle: All favicons from one image
        keywords: favicons multi platform
        url: "https://realfavicongenerator.net/"
        target: "_blank"   
      - name: v0
        logo: "assets/tools/v0.png"
        subtitle: Draft website generator
        keywords: prompt website generator
        url: "https://v0.dev/"
        target: "_blank"  
      
  - name: Comparatives
    icon: fa-solid fa-scale-balanced
    items:
      - name: StackShare
        logo: "assets/tools/stacks.png"
        subtitle: Big companies tech stacks
        keywords: tech stacks companies discover
        url: "https://stackshare.io/stacks"
        target: "_blank"   
      - name: GetDeploying
        logo: "assets/tools/getdeploying.png"
        subtitle: Deployment methods tool
        keywords: deploy cloud providers
        url: "https://getdeploying.com/"
        target: "_blank"   
      - name: OpenSpeedTest
        icon: fas fa-stopwatch
        subtitle: Open-source and reliable speedtest
        tag: self-hosted
        keywords: speedtest opensource
        url: "https://speedtest.mykodelab.dev/"
        target: "_blank" 


  - name: Ressources
    icon: fa-regular fa-window-restore
    items:
      - name: Undesign
        logo: "assets/tools/undesign.png"
        subtitle: Free collections tools and designs
        keywords: collection tools designs opensource rich
        url: "https://undesign.learn.uno/"
        target: "_blank" 
      - name: Coolors
        icon: fas fa-droplet
        subtitle: Color palettes finder
        keywords: colors palettes free
        url: "https://coolors.co/"
        target: "_blank"   
      - name: Devhints
        logo: "assets/tools/devhints.png"
        subtitle: Cheatsheets from @rstacruz
        keywords: cheatsheet personnal dev
        url: "https://devhints.io/"
        target: "_blank"   
      - name: Cheatography
        icon: fas fa-file
        subtitle: General purpose cheatsheets
        keywords: cheatsheets graphy general
        url: "https://cheatography.com/"
        target: "_blank"  

  - name: Learning
    icon: fa-solid fa-graduation-cap
    items:
      - name: Roadmap.sh
        logo: "assets/tools/roadmap.png"
        subtitle: Detailed learning journeys
        keywords: roadmap learning tutorial path journey
        url: "https://roadmap.sh/"
        target: "_blank"
      - name: freeCodeCamp
        logo: "assets/tools/freecodecamp.png"
        subtitle: Programming curriculum for software dev
        keywords: freecodecamp curriculum learning teaching formation
        url: "https://www.freecodecamp.org/learn"
        target: "_blank"
      - name: Exercism
        logo: "assets/tools/exercism.png"
        subtitle: General programming training platform
        keywords: exercism programming exercises code
        url: "https://exercism.org/"
        target: "_blank"
      - name: DataCamp
        logo: "assets/tools/datacamp.png"
        subtitle: Data & AI programming training platform
        keywords: data ai programming platform exercises lessons
        url: "https://app.datacamp.com/"
        target: "_blank"
      - name: Visualgo
        icon: fas fa-diagram-project
        subtitle: Visualising algorithms through animation
        keywords: algo visualisation structures graph
        url: "https://visualgo.net/"
        target: "_blank"         
  
  - name: Media
    icon: fas fa-image
    items:
      - name: Jellyfin
        logo: "assets/tools/jellyfin.png"
        subtitle: Media library for TV shows, movies, books, music...
        tag: self-hosted
        keywords: jellyfin tv media film series movies
        url: "https://tv.mykodelab.dev/"
        target: "_blank"   

  - name: Security
    icon: fas fa-key
    items:
      - name: Bitwarden
        icon: fas fa-shield-halved
        subtitle: OSS Password manager
        tag: self-hosted
        keywords: bitwarden password manager security
        url: "https://vault.mykodelab.dev/"
        target: "_blank"   

  # - name: 
  #   icon: 
  #   items:
  #     - name: 
  #       logo: "assets/tools/.png"
  #       subtitle: 
  #       tag: self-hosted
  #       keywords: 
  #       url: ""
  #       target: "_blank"   
  #     - name: 
  #       logo: "assets/tools/.png"
  #       subtitle: 
  #       tag: self-hosted
  #       keywords: 
  #       url: ""
  #       target: "_blank"                           
      
